services:
  # Identity Provider Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: idp_backend
    restart: always
    env_file: .env
    ports:
      - "8080:8080"
    volumes:
      - ./certs:/app/certs:ro
    networks:
      - identity_network
    depends_on:
      db:
        condition: service_healthy

  # TODO (Kyle): Dockerized frontend
  # Frontend Application

  # Database Service
  db:
    image: mysql:8.4
    container_name: unified_access_database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
    ports:
      - "3360:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./scripts/init.sh:/docker-entrypoint-initdb.d/init.sh:ro
    networks:
      - identity_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Minio (S3-Like storage)
  minio_init:
    image: quay.io/minio/mc:latest
    container_name: idp_minio_setup
    depends_on:
      - minio
    networks:
      - identity_network
    environment:
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
    entrypoint: >
      /bin/sh -c "
      # Wait for MinIO server to be fully ready
      sleep 10;
      # Configure the 'mc' client with an alias named 'local'
      mc alias set local http://minio:9000 ${S3_ACCESS_KEY} ${S3_SECRET_KEY};
      # Create the bucket only if it does not exist
      mc mb local/${S3_BUCKET_NAME} --ignore-existing;
      # Set policy to download (optional: allows public read of images)
      mc anonymous set download local/${S3_BUCKET_NAME};
      exit 0;
      "

volumes:
  db_data:
  minio_data:

networks:
  identity_network:
    driver: bridge